config/routes.rb
Transportview::Application.routes.draw do

  resources :disruptions

  get "disruptions/show"

  get "site/index"

  root :to => 'site#index'
  

end

app/models/disruption.rb
class Disruption
  include Mongoid::Document
  field :lon, type: Float
  field :lat, type: Float
  field :startTime, type: String
  field :endTime, type: String
  field :lastModTime, type: String
  field :comments, type: String
  field :subCategory, type: String
  field :category, type: String
  field :status, type: String
  field :tfl_id, type: Integer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/disruptions_controller.rb
class DisruptionsController < ApplicationController
  # GET /disruptions
  # GET /disruptions.json
  def index
    @disruptions = Disruption.all

    respond_to do |format|
      format.html # index.html.erb
      # format.json { render json: @disruptions }
      format.json # index.json.rabl
    end
  end

  # GET /disruptions/1
  # GET /disruptions/1.json
  def show
    @disruption = Disruption.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @disruption }
    end
  end

  # GET /disruptions/new
  # GET /disruptions/new.json
  def new
    @disruption = Disruption.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @disruption }
    end
  end

  # GET /disruptions/1/edit
  def edit
    @disruption = Disruption.find(params[:id])
  end

  # POST /disruptions
  # POST /disruptions.json
  def create
    @disruption = Disruption.new(params[:disruption])

    respond_to do |format|
      if @disruption.save
        format.html { redirect_to @disruption, notice: 'Disruption was successfully created.' }
        format.json { render json: @disruption, status: :created, location: @disruption }
      else
        format.html { render action: "new" }
        format.json { render json: @disruption.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /disruptions/1
  # PUT /disruptions/1.json
  def update
    @disruption = Disruption.find(params[:id])

    respond_to do |format|
      if @disruption.update_attributes(params[:disruption])
        format.html { redirect_to @disruption, notice: 'Disruption was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @disruption.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disruptions/1
  # DELETE /disruptions/1.json
  def destroy
    @disruption = Disruption.find(params[:id])
    @disruption.destroy

    respond_to do |format|
      format.html { redirect_to disruptions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def nav_link(link_text, link_path)
	  class_name = current_page?(link_path) ? 'active' : ''

	  content_tag(:li, :class => class_name) do
	    link_to link_text, link_path
	  end
	end
	
end

app/helpers/disruptions_helper.rb
module DisruptionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/disruptions/_form.html.erb
<%= form_for(@disruption) do |f| %>
  <% if @disruption.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@disruption.errors.count, "error") %> prohibited this disruption from being saved:</h2>

      <ul>
      <% @disruption.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lon %><br />
    <%= f.text_field :lon %>
  </div>
  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :startTime %><br />
    <%= f.text_field :startTime %>
  </div>
  <div class="field">
    <%= f.label :lastModTime %><br />
    <%= f.text_field :lastModTime %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/disruptions/edit.html.erb
<h1>Editing disruption</h1>

<%= render 'form' %>

<%= link_to 'Show', @disruption %> |
<%= link_to 'Back', disruptions_path %>

app/views/disruptions/index.html.erb
<h1>Listing disruptions</h1>

<table>
  <tr>
    <th>Lon</th>
    <th>Lat</th>
    <th>Starttime</th>
    <th>Lastmodtime</th>
    <th>Comments</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @disruptions.each do |disruption| %>
  <tr>
    <td><%= disruption.lon %></td>
    <td><%= disruption.lat %></td>
    <td><%= disruption.startTime %></td>
    <td><%= disruption.lastModTime %></td>
    <td><%= disruption.comments %></td>
    <td><%= link_to 'Show', disruption %></td>
    <td><%= link_to 'Edit', edit_disruption_path(disruption) %></td>
    <td><%= link_to 'Destroy', disruption, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Disruption', new_disruption_path %>

app/views/disruptions/new.html.erb
<h1>New disruption</h1>

<%= render 'form' %>

<%= link_to 'Back', disruptions_path %>

app/views/disruptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Lon:</b>
  <%= @disruption.lon %>
</p>

<p>
  <b>Lat:</b>
  <%= @disruption.lat %>
</p>

<p>
  <b>Starttime:</b>
  <%= @disruption.startTime %>
</p>

<p>
  <b>Lastmodtime:</b>
  <%= @disruption.lastModTime %>
</p>

<p>
  <b>Comments:</b>
  <%= @disruption.comments %>
</p>


<%= link_to 'Edit', edit_disruption_path(@disruption) %> |
<%= link_to 'Back', disruptions_path %>

app/views/layouts/_body.html.erb
<div class="row">
  <div class="large-12 columns">
    <%= yield %>
  </div>
</div>

app/views/layouts/_charts.html.erb
<div class="row">
  <div class="large-12 columns">
  	<div id="date-chart" class="chart">
		<div class="title">Date</div>
	</div>
	<div id="hour-chart" class="chart">
		<div class="title">Time of Day</div>
	</div>
	<div id="distance-chart" class="chart">
		<div class="title">Distance (miles)</div>
	</div>
	<div id="day-chart" class="chart">
		<div class="title">Day of the Week</div>
	</div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="row">
  <div class="large-12 columns">
    <div class="row">
      <div class="large-12 columns">
        <h6 class='subheader'>
	        By <a href="https://github.com/samuelleach/transportview">Samuel Leach</a>.
			Map tiles by <a href="http://stamen.com">Stamen Design</a>, under <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>. Map data by <a href="http://openstreetmap.org">OpenStreetMap</a>, under <a href="http://creativecommons.org/licenses/by-sa/3.0">CC BY SA</a>. Disruption data from <a href="http://www.tfl.gov.uk/businessandpartners/syndication/16492.aspx">Transport for London</a>. Data rendered with <a href="http://d3js.org">D3</a> and filtered with <a href="http://square.github.io/crossfilter/">Crossfilter</a>.
	    </h6>
      </div>
      <div class="large-6 columns">
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class="nav-bar right">
     <ul class="button-group">
       <li><%= link_to('Reload', root_path, :class => 'button tiny') %></li>
      </ul>
    </div>
    <h2 class='subheader'>TransportView</h2>
  </div>
</div>

app/views/layouts/_tooltip.html.erb
<p></p>

app/views/layouts/_totals.html.erb
	<div class="row">
	<span id="active">-</span> of <span id="total">-</span> disruptions selected.
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.5/leaflet.css" />
<!--link rel="stylesheet" href="http://polymaps.org/style.css" />
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>
  <html class="ie8" lang="en">
<![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "TransportView" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div id='nav'><%= render :partial => 'layouts/nav' %></div>
    <div id='body'><%= render :partial => 'layouts/body' %></div>
    <div id='charts'><%= render :partial => 'layouts/charts' %></div>
    <div id='totals'><%= render :partial => 'layouts/totals' %></div>
    <div id='footer'><%= render :partial => 'layouts/footer' %></div>
    <div id='tooltip' class='hidden'><%= render :partial => 'layouts/tooltip' %></div>

    <!--script src="http://cdn.leafletjs.com/leaflet-0.5/leaflet.js"><!/script-->
    <!--script type="text/javascript" src="http://polymaps.org/polymaps.min.js?2.5.0"><!/script-->
    <script src="js/d3.v3.min.js"></script>
    <script src="js/d3.geo.tile.v0.min.js"></script>
    <script src="js/topojson.v1.min.js"></script>
    <script src="js/crossfilter.min.js"></script>
    <script src="js/queue.v1.min.js"></script>
    <script src="js/geolib.js"></script>
    <%= javascript_include_tag "application" %>
    <script src="js/jquery.xml2json.js" type="text/javascript" language="javascript"></script>
    <script src="js/underscore-min.js" type="text/javascript" language="javascript"></script>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-41794417-1', 'herokuapp.com');
      ga('send', 'pageview');
    </script>

  </body>
</html>

app/views/site/index.html.erb
 <div id="map"></div>
 <div id="messageboard"></div>